# Generated by Django 6.0 on 2025-12-24 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='지문 제목/주제')),
                ('content', models.TextField(blank=True, verbose_name='공통 지문 내용')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100, verbose_name='교재명')),
                ('chapter', models.IntegerField(default=1, verbose_name='강/챕터')),
                ('number', models.IntegerField(default=1, verbose_name='문제 번호')),
                ('category', models.CharField(choices=[('SYNTAX', '구문'), ('GRAMMAR', '어법'), ('READING', '독해')], default='SYNTAX', max_length=10, verbose_name='유형')),
                ('question_text', models.TextField(verbose_name='문제 지문/내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exam_images/', verbose_name='문제 이미지')),
                ('answer', models.CharField(blank=True, max_length=200, verbose_name='정답')),
                ('explanation', models.TextField(blank=True, verbose_name='해설/이유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.questiongroup', verbose_name='지문 그룹')),
            ],
            options={
                'verbose_name': '문제',
                'verbose_name_plural': '문제 관리',
                'ordering': ['book_name', 'chapter', 'number'],
                'unique_together': {('book_name', 'chapter', 'number')},
            },
        ),
        migrations.CreateModel(
            name='TestPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='시험지 제목')),
                ('target_chapters', models.CharField(max_length=200, verbose_name='출제 범위')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questions', models.ManyToManyField(related_name='test_papers', to='exam.question', verbose_name='포함된 문제들')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='응시 학생')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='점수')),
                ('is_passed', models.BooleanField(default=False, verbose_name='통과 여부')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='선생님 피드백')),
                ('date', models.DateField(auto_now_add=True, verbose_name='응시일')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exam.testpaper')),
            ],
        ),
    ]
