# Generated by Django 6.0 on 2025-12-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.CharField(max_length=20, verbose_name='문제 번호'),
        ),
    ]
