# Generated by Django 6.0 on 2025-12-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='exam_answers/', verbose_name='해설 이미지'),
        ),
    ]
