# Generated by Django 6.0 on 2025-12-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_question_answer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='style',
            field=models.CharField(choices=[('CONCEPT', '🟢 개념/이론'), ('ANALYSIS', '🔴 구문분석/적용')], default='CONCEPT', max_length=10, verbose_name='문제 유형'),
        ),
    ]
