# Generated by Django 6.0 on 2025-12-27 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_staffprofile_managed_teachers_staffprofile_position'),
        ('exam', '0004_question_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpaper',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_papers', to='core.studentprofile', verbose_name='응시 학생'),
        ),
    ]
