# Generated by Django 6.0 on 2025-12-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_testpaper_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reading_type',
            field=models.CharField(choices=[('NONE', '해당없음 (구문/개념 등)'), ('TOPIC', 'Type A: 대의파악 (주제/제목/요지)'), ('LOGIC', 'Type B: 논리흐름 (순서/삽입/무관)'), ('BLANK', 'Type C: 빈칸/함축의미'), ('DETAIL', 'Type D: 세부내용 (일치/도표/어휘)'), ('STRUCT', 'Type S: 문장 구조분석 (가로 1단)')], default='NONE', max_length=10, verbose_name='독해 유형'),
        ),
    ]
