# Generated by Django 6.0 on 2025-12-18 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='학생 이름')),
                ('school', models.CharField(blank=True, max_length=30, null=True, verbose_name='학교')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='주소')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='학생 연락처')),
                ('parent_phone_mom', models.CharField(blank=True, max_length=15, null=True, verbose_name='어머님 연락처')),
                ('parent_phone_dad', models.CharField(blank=True, max_length=15, null=True, verbose_name='아버님 연락처')),
                ('syntax_class_time', models.CharField(blank=True, help_text='예: 월요일 18:00', max_length=50, verbose_name='구문 수업 시간')),
                ('reading_class_time', models.CharField(blank=True, help_text='예: 수요일 20:00', max_length=50, verbose_name='독해 수업 시간')),
                ('memo', models.TextField(blank=True, verbose_name='특이사항 메모')),
                ('last_failed_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 도전 실패 시각')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '학생 프로필',
                'verbose_name_plural': '학생 프로필',
            },
        ),
    ]
