# Generated by Django 6.0 on 2025-12-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='last_wrong_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
