# Generated by Django 6.0 on 2026-01-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_studentprofile_attendance_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='notification_recipient',
            field=models.CharField(choices=[('MOM', '어머님만'), ('DAD', '아버님만'), ('BOTH', '부모님 두 분 다')], default='MOM', max_length=10, verbose_name='학부모 알림 수신자'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='send_attendance_alarm',
            field=models.BooleanField(default=True, verbose_name='[알림] 등/하원 문자 발송'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='send_report_alarm',
            field=models.BooleanField(default=True, verbose_name='[알림] 성적표 문자 발송'),
        ),
    ]
