# Generated by Django 6.0 on 2025-12-19 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_school_alter_studentprofile_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='예: 고1 구문 A반', max_length=50, verbose_name='수업명')),
                ('day', models.CharField(choices=[('MON', '월요일'), ('TUE', '화요일'), ('WED', '수요일'), ('THU', '목요일'), ('FRI', '금요일'), ('SAT', '토요일'), ('SUN', '일요일')], max_length=3, verbose_name='요일')),
                ('start_time', models.TimeField(verbose_name='시작 시간')),
                ('end_time', models.TimeField(verbose_name='종료 시간')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='reading_class_time',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='syntax_class_time',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='last_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='reading_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_students', to='core.classtime', verbose_name='독해 수업 선택'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='syntax_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syntax_students', to='core.classtime', verbose_name='구문 수업 선택'),
        ),
    ]
