# Generated by Django 6.0 on 2025-12-19 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_classtime_remove_studentprofile_reading_class_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classtime',
            options={'ordering': ['day', 'start_time'], 'verbose_name': '수업 시간표', 'verbose_name_plural': '수업 시간표'},
        ),
        migrations.AlterField(
            model_name='classtime',
            name='name',
            field=models.CharField(blank=True, default='정규수업', max_length=50, verbose_name='수업명'),
        ),
        migrations.AlterField(
            model_name='school',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='지역'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='reading_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_reading', to='core.classtime', verbose_name='독해 수업 시간'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='syntax_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_syntax', to='core.classtime', verbose_name='구문 수업 시간'),
        ),
    ]
