# Generated by Django 6.0 on 2026-01-07 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_popup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='popups', to='core.branch', verbose_name='소속 지점 (비워두면 전체)'),
        ),
    ]
