# Generated by Django 6.0 on 2025-12-20 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_classtime_options_alter_classtime_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtime',
            name='day',
            field=models.IntegerField(choices=[(0, '월요일'), (1, '화요일'), (2, '수요일'), (3, '목요일'), (4, '금요일'), (5, '토요일'), (6, '일요일')], verbose_name='요일'),
        ),
        migrations.AlterField(
            model_name='classtime',
            name='name',
            field=models.CharField(default='정규수업', max_length=50, verbose_name='수업명'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='reading_class',
            field=models.ForeignKey(blank=True, limit_choices_to={'name__contains': '독해'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_reading', to='core.classtime', verbose_name='독해 수업 선택'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='syntax_class',
            field=models.ForeignKey(blank=True, limit_choices_to={'name__contains': '구문'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_syntax', to='core.classtime', verbose_name='구문 수업 선택'),
        ),
    ]
