# Generated by Django 6.0 on 2025-12-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_classtime_day_alter_classtime_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='attendance_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='출석 코드'),
        ),
    ]
