# Generated by Django 6.0 on 2026-01-11 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_popup_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(choices=[('TEACHER', '일반 강사'), ('VICE', '부원장'), ('PRINCIPAL', '원장'), ('TA', '조교')], default='TEACHER', max_length=10, verbose_name='직책'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='메시지 내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='messages/%Y/%m/%d/', verbose_name='첨부 이미지')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='보낸 시간')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='읽은 시간')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='받는 사람')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='보낸 사람')),
            ],
            options={
                'verbose_name': '메시지',
                'verbose_name_plural': '메시지',
                'ordering': ['-sent_at'],
            },
        ),
    ]
