# Generated by Django 6.0 on 2025-12-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_studentprofile_attendance_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='attendance_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='출석 코드'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='전화번호'),
        ),
    ]
