# Generated by Django 6.0 on 2026-01-13 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_staffprofile_position_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='수업 시작일'),
        ),
    ]
