# Generated by Django 6.0 on 2025-12-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_studentprofile_attendance_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='base_grade',
            field=models.IntegerField(choices=[(1, '초1'), (2, '초2'), (3, '초3'), (4, '초4'), (5, '초5'), (6, '초6'), (7, '중1'), (8, '중2'), (9, '중3'), (10, '고1'), (11, '고2'), (12, '고3'), (13, '졸업/성인')], default=7, verbose_name='기준 학년(가입시)'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='base_year',
            field=models.IntegerField(default=2025, verbose_name='기준 연도(가입년도)'),
        ),
    ]
