# Generated by Django 6.0 on 2026-01-13 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_studentprofile_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='join_date',
            field=models.DateField(default=datetime.date.today, verbose_name='입사일'),
        ),
    ]
