# Generated by Django 6.0 on 2025-12-20 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_studentprofile_base_grade_studentprofile_base_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='지점명')),
            ],
            options={
                'verbose_name': '지점(캠퍼스)',
                'verbose_name_plural': '지점(캠퍼스)',
            },
        ),
        migrations.AlterModelOptions(
            name='classtime',
            options={'verbose_name': '수업 시간표', 'verbose_name_plural': '수업 시간표'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': '학교', 'verbose_name_plural': '학교'},
        ),
        migrations.AlterField(
            model_name='classtime',
            name='day',
            field=models.CharField(choices=[('Mon', '월요일'), ('Tue', '화요일'), ('Wed', '수요일'), ('Thu', '목요일'), ('Fri', '금요일'), ('Sat', '토요일'), ('Sun', '일요일')], max_length=3, verbose_name='요일'),
        ),
        migrations.AlterField(
            model_name='classtime',
            name='name',
            field=models.CharField(max_length=50, verbose_name='수업명 (예: 구문_평일)'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=30, verbose_name='학교명'),
        ),
        migrations.AlterField(
            model_name='school',
            name='region',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='지역'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classtime',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.branch', verbose_name='지점'),
        ),
        migrations.AddField(
            model_name='school',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='schools', to='core.branch', verbose_name='관련 지점'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='소속 지점'),
        ),
    ]
