# Generated by Django 6.0 on 2026-01-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_staffprofile_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='resignation_date',
            field=models.DateField(blank=True, null=True, verbose_name='퇴사일'),
        ),
    ]
