# Generated by Django 6.0 on 2026-01-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_staffprofile_resignation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='memo',
            field=models.TextField(blank=True, verbose_name='메모'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='전화번호'),
        ),
    ]
