# Generated by Django 6.0 on 2025-12-20 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_branch_alter_classtime_options_alter_school_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='reading_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_reading_students', to=settings.AUTH_USER_MODEL, verbose_name='독해 담당쌤'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='syntax_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_syntax_students', to=settings.AUTH_USER_MODEL, verbose_name='구문 담당쌤'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='base_grade',
            field=models.IntegerField(choices=[(1, '초1'), (2, '초2'), (3, '초3'), (4, '초4'), (5, '초5'), (6, '초6'), (7, '중1'), (8, '중2'), (9, '중3'), (10, '고1'), (11, '고2'), (12, '고3'), (13, '졸업/성인')], default=7, verbose_name='기준 학년'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='base_year',
            field=models.IntegerField(default=2025, verbose_name='기준 연도'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='reading_class',
            field=models.ForeignKey(blank=True, limit_choices_to={'name__contains': '독해'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_reading', to='core.classtime', verbose_name='독해 시간표'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='syntax_class',
            field=models.ForeignKey(blank=True, limit_choices_to={'name__contains': '구문'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_syntax', to='core.classtime', verbose_name='구문 시간표'),
        ),
    ]
