# Generated by Django 6.0 on 2026-01-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_staffprofile_memo_staffprofile_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classtime',
            options={'ordering': ['day', 'start_time'], 'verbose_name': '수업 시간표', 'verbose_name_plural': '수업 시간표'},
        ),
        migrations.AddField(
            model_name='classtime',
            name='class_type',
            field=models.CharField(choices=[('SYNTAX', '구문'), ('READING', '독해'), ('EXTRA', '특강/기타')], default='EXTRA', max_length=10, verbose_name='수업 유형'),
        ),
    ]
