# Generated by Django 6.0 on 2025-12-20 18:35

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0011_studentprofile_reading_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffUser',
            fields=[
            ],
            options={
                'verbose_name': '선생님 계정',
                'verbose_name_plural': '선생님 계정 관리',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
