# Generated by Django 6.0 on 2025-12-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_staffuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffUser',
        ),
    ]
