# Generated by Django 6.0 on 2026-01-14 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_classtime_options_classtime_class_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='extra_class_category',
            field=models.CharField(choices=[('SYNTAX', '구문'), ('READING', '독해'), ('MOCK', '모의고사'), ('EXTRA', '특강/기타')], default='EXTRA', max_length=10, verbose_name='특강 종류 (구문/독해/모의고사)'),
        ),
        migrations.AlterField(
            model_name='classtime',
            name='class_type',
            field=models.CharField(choices=[('SYNTAX', '구문'), ('READING', '독해'), ('MOCK', '모의고사'), ('EXTRA', '특강/기타')], default='EXTRA', max_length=10, verbose_name='수업 유형'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='extra_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_extra', to='core.classtime', verbose_name='특강 시간표'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='extra_class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_extra_teacher', to=settings.AUTH_USER_MODEL, verbose_name='특강 담당 선생님'),
        ),
    ]
