# Generated by Django 6.0 on 2025-12-20 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_staffuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='reading_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'staff_profile__is_reading_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_reading_students', to=settings.AUTH_USER_MODEL, verbose_name='독해 담당쌤'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='syntax_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'staff_profile__is_syntax_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_syntax_students', to=settings.AUTH_USER_MODEL, verbose_name='구문 담당쌤'),
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_syntax_teacher', models.BooleanField(default=False, verbose_name='구문 수업 가능')),
                ('is_reading_teacher', models.BooleanField(default=False, verbose_name='독해 수업 가능')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
