# Generated by Django 6.0 on 2025-12-22 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_studentprofile_reading_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='소속 지점'),
        ),
    ]
