# Generated by Django 6.0 on 2025-12-22 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_classtime_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtime',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='reading_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'staff_profile__is_reading_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_students', to=settings.AUTH_USER_MODEL, verbose_name='독해 담당 선생님'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='syntax_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'staff_profile__is_syntax_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syntax_students', to=settings.AUTH_USER_MODEL, verbose_name='구문 담당 선생님'),
        ),
    ]
