# Generated by Django 6.0 on 2025-12-22 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_classtime_teacher_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='extra_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_extra', to='core.classtime', verbose_name='추가 수업 시간'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='extra_class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_students', to=settings.AUTH_USER_MODEL, verbose_name='추가 수업 담당 선생님'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='extra_class_type',
            field=models.CharField(blank=True, choices=[('SYNTAX', '구문'), ('READING', '독해')], max_length=10, null=True, verbose_name='추가 수업 종류'),
        ),
    ]
