# Generated by Django 6.0 on 2025-12-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_studentprofile_extra_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='선생님 성함'),
        ),
    ]
