# Generated by Django 6.0 on 2025-12-22 23:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_staffprofile_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='managed_teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_staff': True}, related_name='managers', to=settings.AUTH_USER_MODEL, verbose_name='[부원장용] 담당 강사 선택'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(choices=[('TEACHER', '일반 강사'), ('VICE', '부원장')], default='TEACHER', max_length=10, verbose_name='직책'),
        ),
    ]
