# Generated by Django 6.0 on 2026-01-07 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_popup_branch'),
        ('vocab', '0003_rankingevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingevent',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.branch', verbose_name='진행 지점 (비워두면 전체)'),
        ),
    ]
