# Generated by Django 6.0 on 2026-01-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0004_rankingevent_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalwrongword',
            name='last_correct_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalwrongword',
            name='success_count',
            field=models.IntegerField(default=0),
        ),
    ]
