# Generated by Django 6.0 on 2026-01-12 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_staffprofile_position_message'),
        ('vocab', '0005_personalwrongword_last_correct_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='영단어')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='personalwrongword',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocab.word'),
        ),
        migrations.AlterUniqueTogether(
            name='personalwrongword',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='personalwrongword',
            name='master_word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vocab.masterword', verbose_name='마스터 단어'),
        ),
        migrations.AddField(
            model_name='word',
            name='master_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_entries', to='vocab.masterword', verbose_name='마스터 단어 링크'),
        ),
        migrations.AlterUniqueTogether(
            name='personalwrongword',
            unique_together={('student', 'master_word')},
        ),
        migrations.CreateModel(
            name='WordMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=100, verbose_name='뜻')),
                ('source', models.CharField(blank=True, max_length=50, verbose_name='출처/뉘앙스')),
                ('master_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='vocab.masterword')),
            ],
            options={
                'unique_together': {('master_word', 'meaning')},
            },
        ),
    ]
