# Generated by Django 6.0 on 2026-01-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0006_masterword_alter_personalwrongword_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordmeaning',
            name='pos',
            field=models.CharField(choices=[('n', '명사'), ('v', '동사'), ('adj', '형용사'), ('adv', '부사'), ('pron', '대명사'), ('prep', '전치사'), ('conj', '접속사'), ('interj', '감탄사')], default='n', max_length=10, verbose_name='품사'),
        ),
    ]
