# Generated by Django 6.0 on 2026-01-12 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0007_wordmeaning_pos'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=set(),
        ),
    ]
