# Generated by Django 6.0 on 2026-01-12 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_staffprofile_position_message'),
        ('vocab', '0008_alter_word_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordbook',
            name='target_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='대상 지점 (본사=NULL)'),
        ),
        migrations.AddField(
            model_name='wordbook',
            name='target_grade',
            field=models.IntegerField(blank=True, null=True, verbose_name='대상 학년 (전체=NULL)'),
        ),
        migrations.AddField(
            model_name='wordbook',
            name='target_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.school', verbose_name='대상 학교'),
        ),
    ]
