# Generated by Django 6.0 on 2026-01-12 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_staffprofile_position_message'),
        ('vocab', '0009_wordbook_target_branch_wordbook_target_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalWordBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='vocab.wordbook')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_books', to='core.studentprofile')),
            ],
            options={
                'verbose_name': '나의 단어장',
                'verbose_name_plural': '나의 단어장',
                'unique_together': {('student', 'book')},
            },
        ),
    ]
