# Generated by Django 6.0.1 on 2026-01-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0011_testresult_assignment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresultdetail',
            name='question_pos',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='문제 품사'),
        ),
    ]
