# Generated by Django 6.0.1 on 2026-01-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0012_testresultdetail_question_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordbook',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='covers/', verbose_name='표지/배경 이미지'),
        ),
    ]
