# Generated by Django 6.0 on 2025-12-18 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(verbose_name='시험 날짜')),
                ('syntax_score', models.IntegerField(default=0, verbose_name='구문 점수')),
                ('reading_score', models.IntegerField(default=0, verbose_name='독해 점수')),
                ('feedback', models.TextField(blank=True, verbose_name='선생님 코멘트')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '구문/독해 점수(오프라인)',
                'verbose_name_plural': '구문/독해 점수(오프라인)',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='년도')),
                ('month', models.IntegerField(verbose_name='월')),
                ('average_word_score', models.FloatField(help_text='도전모드/월말평가 평균', verbose_name='단어 평균 점수')),
                ('syntax_score', models.IntegerField(verbose_name='구문 점수')),
                ('reading_score', models.IntegerField(verbose_name='독해 점수')),
                ('overall_comment', models.TextField(verbose_name='종합 평가')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '최종 월말 성적표',
                'verbose_name_plural': '최종 월말 성적표',
                'unique_together': {('student', 'year', 'month')},
            },
        ),
    ]
