# Generated by Django 6.0 on 2026-01-11 21:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_staffprofile_position_message'),
        ('reports', '0002_alter_monthlyreport_month_alter_monthlyreport_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='공유 링크 키')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('expires_at', models.DateTimeField(verbose_name='만료일')),
                ('access_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studentprofile', verbose_name='학생')),
            ],
            options={
                'verbose_name': '성적표 공유 링크',
                'verbose_name_plural': '성적표 공유 링크 관리',
            },
        ),
    ]
