# Generated by Django 6.0.1 on 2026-01-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0004_mockexam_student_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockexam',
            name='wrong_type_breakdown',
            field=models.JSONField(blank=True, default=dict, verbose_name='유형별 오답 분석'),
        ),
    ]
