# Generated by Django 6.0.1 on 2026-01-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0005_mockexam_wrong_type_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockexaminfo',
            name='institution',
            field=models.CharField(default='교육청', max_length=50, verbose_name='주관/출판사'),
        ),
    ]
