# Generated by Django 6.0.1 on 2026-01-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0006_mockexaminfo_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockexaminfo',
            name='month',
            field=models.IntegerField(blank=True, null=True, verbose_name='월'),
        ),
        migrations.AlterField(
            model_name='mockexaminfo',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='연도'),
        ),
    ]
