# Generated by Django 6.0 on 2025-12-20 19:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0014_alter_studentprofile_reading_teacher_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='교재명')),
                ('publisher', models.CharField(blank=True, max_length=50, verbose_name='출판사')),
                ('level', models.CharField(blank=True, max_length=20, verbose_name='레벨')),
            ],
        ),
        migrations.CreateModel(
            name='ClassLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='수업 날짜')),
                ('comment', models.TextField(blank=True, verbose_name='선생님 코멘트')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_logs', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '수업 일지',
                'verbose_name_plural': '수업 일지',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TemporarySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('SYNTAX', '구문'), ('READING', '독해')], default='SYNTAX', max_length=10, verbose_name='보강 과목')),
                ('is_extra_class', models.BooleanField(default=False, help_text="체크하면 '기존 수업일(Original Date)'을 입력하지 않아도 됩니다.", verbose_name='추가 보충 여부')),
                ('original_date', models.DateField(blank=True, null=True, verbose_name='기존 수업일 (결석/변경 시)')),
                ('new_date', models.DateField(verbose_name='보강/변경 날짜')),
                ('new_start_time', models.TimeField(blank=True, null=True, verbose_name='시작 시간')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='사유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_schedules', to='core.studentprofile', verbose_name='학생')),
                ('target_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classtime', verbose_name='기존 시간표에서 선택')),
            ],
            options={
                'verbose_name': '보강 및 일정 변경',
                'verbose_name_plural': '보강 및 일정 변경',
            },
        ),
        migrations.CreateModel(
            name='ClassLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_range', models.CharField(max_length=100, verbose_name='진도 범위')),
                ('score', models.CharField(blank=True, choices=[('A', 'A (우수)'), ('B', 'B (보통)'), ('C', 'C (미흡)'), ('F', 'F (재시험)')], max_length=2, null=True, verbose_name='성취도')),
                ('class_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='academy.classlog')),
                ('textbook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.textbook', verbose_name='교재')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='날짜')),
                ('arrived_at', models.DateTimeField(blank=True, null=True, verbose_name='등원 시간')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='하원 시간')),
                ('status', models.CharField(choices=[('PRESENT', '✅ 출석'), ('LATE', '⚠️ 지각'), ('ABSENT', '❌ 결석')], default='ABSENT', max_length=10, verbose_name='상태')),
                ('message_sent', models.BooleanField(default=False, verbose_name='알림 발송 여부')),
                ('memo', models.CharField(blank=True, max_length=50, verbose_name='비고')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '일일 출석부',
                'verbose_name_plural': '일일 출석부',
                'unique_together': {('student', 'date')},
            },
        ),
    ]
