# Generated by Django 6.0 on 2025-12-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlogentry',
            name='unit_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='진도(숫자)'),
        ),
        migrations.AddField(
            model_name='textbook',
            name='category',
            field=models.CharField(choices=[('VOCAB', '📕 단어장'), ('SYNTAX', '📘 구문 교재'), ('READING', '📙 독해 교재'), ('COMMON', '📒 공통 교재')], default='VOCAB', max_length=10, verbose_name='교재 유형'),
        ),
        migrations.AddField(
            model_name='textbook',
            name='total_units',
            field=models.IntegerField(default=0, verbose_name='총 챕터/강 수 (그래프용)'),
        ),
        migrations.AlterField(
            model_name='classlogentry',
            name='progress_range',
            field=models.CharField(max_length=100, verbose_name='진도 범위(텍스트)'),
        ),
    ]
