# Generated by Django 6.0 on 2025-12-22 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_classlogentry_unit_num_textbook_category_and_more'),
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textbook',
            options={'ordering': ['category', 'title'], 'verbose_name': '교재', 'verbose_name_plural': '교재'},
        ),
        migrations.AddField(
            model_name='classlogentry',
            name='wordbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocab.wordbook', verbose_name='단어장'),
        ),
        migrations.AlterField(
            model_name='classlogentry',
            name='textbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.textbook', verbose_name='교재'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='category',
            field=models.CharField(choices=[('SYNTAX', '📘 구문 교재'), ('READING', '📙 독해 교재')], default='SYNTAX', max_length=10, verbose_name='교재 유형'),
        ),
    ]
