# Generated by Django 6.0 on 2025-12-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_alter_textbook_options_classlogentry_wordbook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlogentry',
            name='unit_num',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='진도(숫자 또는 범위)'),
        ),
    ]
