# Generated by Django 6.0 on 2026-01-11 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_alter_textbook_category'),
        ('core', '0007_alter_staffprofile_position_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('VIDEO', '인강'), ('WORKBOOK', '교재'), ('VOCAB', '단어'), ('OTHER', '기타')], default='OTHER', max_length=10, verbose_name='과제 유형')),
                ('title', models.CharField(max_length=100, verbose_name='과제명')),
                ('description', models.TextField(blank=True, verbose_name='상세 설명')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='자지정일')),
                ('due_date', models.DateField(verbose_name='마감일(하는 날)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.studentprofile', verbose_name='학생')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='담당 선생님')),
            ],
            options={
                'verbose_name': '주간 과제',
                'verbose_name_plural': '주간 과제',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='assignments/%Y/%m/%d/', verbose_name='인증샷')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='제출 시간')),
                ('status', models.CharField(choices=[('PENDING', '검사 대기'), ('APPROVED', '승인(완료)'), ('REJECTED', '반려(재제출)')], default='PENDING', max_length=10, verbose_name='상태')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='선생님 피드백')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='검사 시간')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studentprofile', verbose_name='제출 학생')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='academy.assignmenttask', verbose_name='관련 과제')),
            ],
            options={
                'verbose_name': '과제 인증',
                'verbose_name_plural': '과제 인증',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
