# Generated by Django 6.0 on 2025-12-22 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_alter_classlogentry_unit_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlogentry',
            name='unit_num',
        ),
        migrations.AddField(
            model_name='classlog',
            name='next_hw_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='다음 과제 끝 강'),
        ),
        migrations.AddField(
            model_name='classlog',
            name='next_hw_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='다음 과제 시작 강'),
        ),
        migrations.AddField(
            model_name='classlog',
            name='teacher_comment',
            field=models.TextField(blank=True, verbose_name='선생님 코멘트 (과제용)'),
        ),
        migrations.AlterField(
            model_name='classlogentry',
            name='progress_range',
            field=models.CharField(max_length=20, verbose_name='진도 범위(숫자)'),
        ),
        migrations.CreateModel(
            name='TextbookUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField(verbose_name='강 번호')),
                ('link_url', models.URLField(blank=True, verbose_name='링크 URL')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='academy.textbook', verbose_name='교재')),
            ],
            options={
                'verbose_name': '교재 단원',
                'verbose_name_plural': '교재 단원',
                'ordering': ['textbook', 'unit_number'],
                'unique_together': {('textbook', 'unit_number')},
            },
        ),
    ]
