# Generated by Django 6.0 on 2026-01-12 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_assignmenttask_assignmentsubmission'),
        ('vocab', '0005_personalwrongword_last_correct_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmenttask',
            name='assigned_date',
        ),
        migrations.RemoveField(
            model_name='assignmenttask',
            name='category',
        ),
        migrations.AddField(
            model_name='assignmenttask',
            name='assignment_type',
            field=models.CharField(choices=[('MANUAL', '일반 (사진 인증)'), ('VOCAB_TEST', '단어 시험 (앱 연동)')], default='MANUAL', max_length=20, verbose_name='과제 유형'),
        ),
        migrations.AddField(
            model_name='assignmenttask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='완료 일시'),
        ),
        migrations.AddField(
            model_name='assignmenttask',
            name='is_rejected',
            field=models.BooleanField(default=False, verbose_name='반려됨'),
        ),
        migrations.AddField(
            model_name='assignmenttask',
            name='origin_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_assignments', to='academy.classlog', verbose_name='출처 수업일지'),
        ),
        migrations.AddField(
            model_name='assignmenttask',
            name='related_vocab_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocab.wordbook', verbose_name='대상 단어장 (Type B)'),
        ),
        migrations.AddField(
            model_name='assignmenttask',
            name='resubmission_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='재제출 마감일'),
        ),
        migrations.AddField(
            model_name='assignmenttask',
            name='vocab_range_end',
            field=models.IntegerField(default=0, verbose_name='종료 Day'),
        ),
        migrations.AddField(
            model_name='assignmenttask',
            name='vocab_range_start',
            field=models.IntegerField(default=0, verbose_name='시작 Day'),
        ),
        migrations.AddField(
            model_name='classlog',
            name='hw_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='과제 마감일'),
        ),
        migrations.AlterField(
            model_name='assignmenttask',
            name='description',
            field=models.TextField(blank=True, verbose_name='상세 내용'),
        ),
        migrations.AlterField(
            model_name='assignmenttask',
            name='due_date',
            field=models.DateField(verbose_name='마감일'),
        ),
        migrations.AlterField(
            model_name='assignmenttask',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
    ]
