# Generated by Django 6.0 on 2025-12-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_remove_classlogentry_unit_num_classlog_next_hw_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', '✅ 출석'), ('LATE', '⚠️ 지각'), ('ABSENT', '❌ 결석')], default='PRESENT', max_length=10, verbose_name='상태'),
        ),
    ]
