# Generated by Django 6.0 on 2026-01-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_remove_assignmenttask_assigned_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='has_ot',
            field=models.BooleanField(default=False, verbose_name='OT 강의 여부'),
        ),
    ]
