# Generated by Django 6.0 on 2025-12-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlog',
            name='subject',
            field=models.CharField(choices=[('SYNTAX', '구문'), ('READING', '독해')], default='SYNTAX', max_length=20, verbose_name='과목'),
        ),
    ]
