# Generated by Django 6.0 on 2026-01-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_textbook_has_ot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmenttask',
            name='due_date',
            field=models.DateTimeField(verbose_name='마감일'),
        ),
        migrations.AlterField(
            model_name='classlog',
            name='hw_due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='과제 마감일'),
        ),
    ]
