# Generated by Django 6.0 on 2026-01-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_alter_assignmenttask_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmenttask',
            name='is_cumulative',
            field=models.BooleanField(default=False, help_text='체크 시 이전 범위도 함께 포함', verbose_name='누적 범위 여부'),
        ),
    ]
