# Generated by Django 6.0 on 2025-12-22 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_classlog_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='arrived_at',
            new_name='check_in_time',
        ),
    ]
