# Generated by Django 6.0 on 2025-12-23 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_rename_arrived_at_attendance_check_in_time'),
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlog',
            name='hw_main_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hw_logs', to='academy.textbook', verbose_name='과제 주교재'),
        ),
        migrations.AddField(
            model_name='classlog',
            name='hw_main_range',
            field=models.CharField(blank=True, max_length=50, verbose_name='과제 진도 범위'),
        ),
        migrations.AddField(
            model_name='classlog',
            name='hw_vocab_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hw_logs', to='vocab.wordbook', verbose_name='과제 단어장'),
        ),
        migrations.AddField(
            model_name='classlog',
            name='hw_vocab_range',
            field=models.CharField(blank=True, max_length=50, verbose_name='과제 단어 범위'),
        ),
        migrations.AddField(
            model_name='classlog',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='알림 발송 시간'),
        ),
        migrations.AlterField(
            model_name='classlogentry',
            name='score',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='성취도/점수'),
        ),
    ]
