# Generated by Django 6.0 on 2025-12-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_classlog_hw_main_book_classlog_hw_main_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlog',
            name='subject',
            field=models.CharField(choices=[('SYNTAX', '구문'), ('READING', '독해'), ('GRAMMAR', '어법')], default='SYNTAX', max_length=20, verbose_name='과목'),
        ),
        migrations.AlterField(
            model_name='temporaryschedule',
            name='subject',
            field=models.CharField(choices=[('SYNTAX', '구문'), ('READING', '독해'), ('GRAMMAR', '어법')], default='SYNTAX', max_length=10, verbose_name='보강 과목'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='category',
            field=models.CharField(choices=[('SYNTAX', '📘 구문 교재'), ('READING', '📙 독해 교재'), ('GRAMMAR', '📗 어법 교재')], default='SYNTAX', max_length=10, verbose_name='교재 유형'),
        ),
    ]
