# Generated by Django 6.0 on 2026-01-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_assignmentsubmissionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmenttask',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='자동 계산됨. 이 날짜 이전에는 학생이 과제 수행 불가', null=True, verbose_name='수행 가능 시작일'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmissionimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
