# Generated by Django 6.0.1 on 2026-01-28 15:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_add_start_date_to_assignment'),
        ('core', '0014_announcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmenttask',
            name='related_textbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.textbook', verbose_name='대상 교재'),
        ),
        migrations.AddField(
            model_name='assignmenttask',
            name='textbook_range',
            field=models.CharField(blank=True, help_text='시작강-끝강 형태로 입력', max_length=20, verbose_name='교재 범위 (예: 1-3)'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='category',
            field=models.CharField(choices=[('SYNTAX', '📘 구문 교재'), ('READING', '📙 독해 교재'), ('GRAMMAR', '📗 어법 교재'), ('LISTENING', '🎧 듣기 교재'), ('SCHOOL_EXAM', '🏫 내신 대비'), ('MOCK_EXAM', '🎓 모의고사')], default='SYNTAX', max_length=12, verbose_name='교재 유형'),
        ),
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=100, verbose_name='성적표 제목')),
                ('start_date', models.DateField(verbose_name='조회 시작일')),
                ('end_date', models.DateField(verbose_name='조회 종료일')),
                ('data_snapshot', models.JSONField(default=dict, verbose_name='데이터 스냅샷')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='선생님 총평')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_reports', to='core.studentprofile', verbose_name='학생')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='발행 선생님')),
            ],
            options={
                'verbose_name': '성적표',
                'verbose_name_plural': '성적표 관리',
                'ordering': ['-created_at'],
            },
        ),
    ]
